#!/usr/bin/env python3
"""Render the session lamp bitmaps (radial lens + LED dot matrix, no bezel)
into LVGL RGB565 C arrays (main/lamp_imgs.c/.h) and PNG previews
(tools/preview/*.png).

Style reference: a traffic-light style indicator — bright warm core fading to
a saturated dark rim, honeycomb LED texture.
"""
import math
import os

S = 164                  # canvas size (square), matches the ring-gauge diameter
R_LENS = S / 2 - 2       # lens radius
DOT_GAP = 6.0            # LED dot grid spacing
DOT_R = 2.1              # LED dot radius

HERE = os.path.dirname(os.path.abspath(__file__))
OUT_C = os.path.join(HERE, "..", "main", "lamp_imgs.c")
OUT_H = os.path.join(HERE, "..", "main", "lamp_imgs.h")
PREVIEW = os.path.join(HERE, "preview")

# state -> (center colour, edge colour)
STATES = {
    "red":    ((1.00, 0.80, 0.42), (0.52, 0.04, 0.02)),
    "yellow": ((1.00, 0.95, 0.60), (0.60, 0.38, 0.02)),
    "green":  ((0.80, 1.00, 0.52), (0.05, 0.36, 0.03)),
    "gray":   ((0.52, 0.54, 0.56), (0.09, 0.09, 0.10)),
}


def clamp(x, lo=0.0, hi=1.0):
    return lo if x < lo else hi if x > hi else x


def smoothstep(a, b, x):
    t = clamp((x - a) / (b - a))
    return t * t * (3 - 2 * t)


def mix(c1, c2, t):
    return tuple(a + (b - a) * t for a, b in zip(c1, c2))


def render(center_col, edge_col, lens_dim=1.0):
    """One RGB image as a flat list of (r,g,b) float tuples."""
    px = [(0.0, 0.0, 0.0)] * (S * S)
    c = S / 2
    for y in range(S):
        dy = y + 0.5 - c
        for x in range(S):
            dx = x + 0.5 - c
            r = math.hypot(dx, dy)
            col = (0.0, 0.0, 0.0)

            # --- lens: radial gradient + LED dots + specular ------------
            a = clamp(R_LENS - r + 0.5)
            if a > 0:
                t = r / R_LENS
                grad = (1.0 - smoothstep(0.0, 0.98, t)) ** 1.25
                lens = mix(edge_col, center_col, grad)

                qx = (dx % DOT_GAP) - DOT_GAP / 2
                qy = (dy % DOT_GAP) - DOT_GAP / 2
                dd = math.hypot(qx, qy)
                inside = clamp((DOT_R - dd) / 1.2 + 0.5)
                dotf = 0.68 + 0.32 * inside + 0.22 * inside * clamp(1 - dd / DOT_R)
                lens = tuple(v * dotf for v in lens)

                spec = math.exp(-(((dx + 26) / 32.0) ** 2 + ((dy + 32) / 28.0) ** 2))
                lens = tuple(v + 0.15 * spec * (1 - 0.5 * t) for v in lens)

                fall = 1.0 - 0.45 * smoothstep(0.82, 1.0, t)
                lens = tuple(clamp(v * fall * lens_dim) for v in lens)
                col = mix(col, lens, a)

            px[y * S + x] = col
    return px


def to_rgb565(px):
    # Big-endian bytes: the firmware builds with CONFIG_LV_COLOR_16_SWAP=y,
    # which makes LVGL read CF_TRUE_COLOR image data byte-swapped.
    out = bytearray()
    for r, g, b in px:
        v = (int(clamp(r) * 31 + 0.5) << 11) | \
            (int(clamp(g) * 63 + 0.5) << 5) | \
            int(clamp(b) * 31 + 0.5)
        out += bytes((v >> 8, v & 0xFF))
    return out


def write_c(images):
    with open(OUT_H, "w") as f:
        f.write("#pragma once\n\n#include \"lvgl.h\"\n\n")
        for name in images:
            f.write(f"extern const lv_img_dsc_t lamp_{name};\n")

    with open(OUT_C, "w") as f:
        f.write('/* Generated by tools/gen_lamp.py — do not edit. */\n')
        f.write('#include "lamp_imgs.h"\n\n')
        for name, data in images.items():
            f.write(f"static const uint8_t lamp_{name}_map[{len(data)}] = {{\n")
            for i in range(0, len(data), 16):
                f.write("    " + ", ".join(f"0x{b:02x}" for b in data[i:i + 16]) + ",\n")
            f.write("};\n\n")
            f.write(f"const lv_img_dsc_t lamp_{name} = {{\n")
            f.write("    .header.cf = LV_IMG_CF_TRUE_COLOR,\n")
            f.write("    .header.always_zero = 0,\n")
            f.write("    .header.reserved = 0,\n")
            f.write(f"    .header.w = {S},\n")
            f.write(f"    .header.h = {S},\n")
            f.write(f"    .data_size = {len(data)},\n")
            f.write(f"    .data = lamp_{name}_map,\n")
            f.write("};\n\n")


def write_previews(images_rgb):
    from PIL import Image
    os.makedirs(PREVIEW, exist_ok=True)
    sheet = Image.new("RGB", (S * len(images_rgb), S), (0, 0, 0))
    for i, (name, px) in enumerate(images_rgb.items()):
        img = Image.new("RGB", (S, S))
        img.putdata([(int(clamp(r) * 255), int(clamp(g) * 255), int(clamp(b) * 255))
                     for r, g, b in px])
        img.save(os.path.join(PREVIEW, f"lamp_{name}.png"))
        sheet.paste(img, (i * S, 0))
    sheet.save(os.path.join(PREVIEW, "sheet.png"))


def main():
    images_rgb = {}
    for name, (center, edge) in STATES.items():
        images_rgb[name] = render(center, edge)
    images_rgb["red_dim"] = render(*STATES["red"], lens_dim=0.22)

    write_c({name: to_rgb565(px) for name, px in images_rgb.items()})
    try:
        write_previews(images_rgb)
        print(f"previews -> {os.path.relpath(PREVIEW)}")
    except ImportError:
        print("Pillow not available, skipped previews")
    print(f"C arrays -> {os.path.relpath(OUT_C)}")


if __name__ == "__main__":
    main()
